repos:
- repo: https://github.com/pre-commit/pre-commit-hooks.git
  rev: 2c9f875913ee60ca25ce70243dc24d5b6415598c
  hooks:
  - id: check-yaml
  - id: check-json
  - id: check-merge-conflict
  - id: check-shebang-scripts-are-executable
  - id: end-of-file-fixer
  - id: fix-byte-order-marker
  - id: mixed-line-ending
-   repo: local
    hooks:
    -   id: naive-check-merge-conflict
        name: naive check-merge-conflict
        entry: '^(<<<<<<< |======= |>>>>>>> |=======$)'
        language: pygrep
# - repo: https://github.com/markdownlint/markdownlint.git
#   rev: 54b2597eb40d50a16a51d717744239d52218fd5b
#   hooks:
#   - id: markdownlint
